#!/bin/sh -e
# Copyright 2020 Erik Lönroth
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    echo "Running from a venv"
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="./src:./lib"
else
    export PYTHONPATH="./src:./lib:$PYTHONPATH"
fi

echo "PYTHONPATH=$PYTHONPATH"
python3 -m unittest -v "$@"
